### ISSUE TITLE
关于图像特征抽取

### ISSUE THREAD

**Issue by AvalonSama** [xunan0812/MIMN#3]
请问您这边抽图像特征的时候是怎么做的啊，我用您的代码抽取图像特征64g的内存就爆了。。

**Comment by 18765751933** [comment]
我也想知道怎么回事，读取数据的时候  图像这一块一跑就爆内存

**Comment by LXM0708** [comment]
> 请问您这边抽图像特征的时候是怎么做的啊，我用您的代码抽取图像特征64g的内存就爆了。。

请问您这个问题解决了吗？小白求带

**Comment by xunan0812** [comment]
在服务器上运行的，当时没有考虑内存的问题，建议改小每次读取的数量，祝好！

**Comment by Dreamupers** [comment]
> 我也想知道怎么回事，读取数据的时候 图像这一块一跑就爆内存

> 请问您这边抽图像特征的时候是怎么做的啊，我用您的代码抽取图像特征64g的内存就爆了。。

[https://github.com/xunan0812/MIMN/blob/8d6e1fe87713243d43b03b32a49245e00001ee7f/data_utils.py#L308]()
1、经过测试发现，RAM在每次执行cnn_extractor时就会快速增加，直到内存爆满。
代码使用CPU进行特征提取，如果将cnn_extractor和input都转化到GPU上，output再转回cpu，问题变为Out of CUDA memory。

[https://github.com/xunan0812/MIMN/blob/8d6e1fe87713243d43b03b32a49245e00001ee7f/data_utils.py#L385](url)
2、另外论文中提到，对图片resize到224×224，但实际上并没有在transform中找到相关代码，导致图片尺寸过大，对于图片很多的某条评论，显存会OOM。

解决办法：使用`with torch.no_grad():`对`output = self.cnn_extractor(input).squeeze()`进行包裹。在`self.transform_img`中添加`transforms.Resize(224)`。（使用CPU提取特征的话，不进行resize应该也可以，因为RAM往往都比显存大很多。另：可以使用GPU更快的提取特征，但要进行resize，不知道会不会影响模型效果。）

**Comment by SouthCity** [comment]
> > 我也想知道怎么回事，读取数据的时候 图像这一块一跑就爆内存
> 
> > 请问您这边抽图像特征的时候是怎么做的啊，我用您的代码抽取图像特征64g的内存就爆了。。
> 
> https://github.com/xunan0812/MIMN/blob/8d6e1fe87713243d43b03b32a49245e00001ee7f/data_utils.py#L308 1、经过测试发现，RAM在每次执行cnn_extractor时就会快速增加，直到内存爆满。 代码使用CPU进行特征提取，如果将cnn_extractor和input都转化到GPU上，output再转回cpu，问题变为Out of CUDA memory。
> 
> [https://github.com/xunan0812/MIMN/blob/8d6e1fe87713243d43b03b32a49245e00001ee7f/data_utils.py#L385](url) 2、另外论文中提到，对图片resize到224×224，但实际上并没有在transform中找到相关代码，导致图片尺寸过大，对于图片很多的某条评论，显存会OOM。
> 
> 解决办法：使用`with torch.no_grad():`对`output = self.cnn_extractor(input).squeeze()`进行包裹。在`self.transform_img`中添加`transforms.Resize(224)`。（使用CPU提取特征的话，不进行resize应该也可以，因为RAM往往都比显存大很多。另：可以使用GPU更快的提取特征，但要进行resize，不知道会不会影响模型效果。）

哇 谢谢老哥。。真的发现一百多g内存都爆掉了。原来是这个问题
