### ISSUE TITLE
关于图像特征抽取

### ISSUE THREAD

**Issue by 18765751933** [xunan0812/MIMN#4]
想问下老师，您关于图像特征的抽取是怎么处理的，为什么我这边读数据的时候内存叫爆了

**Comment by JazzTheSaver** [comment]
我也遇到这个问题。。同样希望老师能够解惑

**Comment by LXM0708** [comment]
> 想问下老师，您关于图像特征的抽取是怎么处理的，为什么我这边读数据的时候内存叫爆了

请问您问题解决了吗？我也遇到了这个问题呢

**Comment by LXM0708** [comment]
> 我也遇到这个问题。。同样希望老师能够解惑

请问你这个问题解决了吗？

**Comment by xunan0812** [comment]
在服务器上运行的，当时没有考虑内存的问题，建议改小每次读取的数量，祝好！
