### ISSUE TITLE
img.zip 数据集解压错误

### ISSUE THREAD

**Issue by zhangxiann** [xunan0812/MIMN#5]
你好，你提供的数据集，其中有个压缩包是 `img.zip`，尝试使用多种软件，均有解压错误：其中有些图片解压失败。
1. 百度云在线解压，提示 `压缩包已损坏，无法解压`。
![image](https://user-images.githubusercontent.com/12131262/133706922-e008fe73-b7f1-45ca-aab5-dd983b65eb63.png)
2. 下载到本地使用 7zip 解压，提示有 8623 张图片解压错误，`数据不可用`。
![image](https://user-images.githubusercontent.com/12131262/133707491-ecf8852a-459b-4a54-b52b-6daf5b439ca2.png)

由于您的论文中提到的 contribution 之一是：

**We provide a new publicly available multimodal aspectlevel sentiment dataset to evaluate our model.**

所以，麻烦您提供切实可用的数据集。谢谢。
**麻烦提供切实可用的数据集，否则我认为你的论文实验数据是不可复现的。**

**Comment by zhangxiann** [comment]
3. 代码里的路径是写死的：`data_utils.py` 的 306 行读取图片的代码是写死路径的，请提供 bug free 可运行的代码。[https://github.com/xunan0812/MIMN/blob/master/data_utils.py#L306](https://github.com/xunan0812/MIMN/blob/master/data_utils.py#L306)

**Comment by xunan0812** [comment]
同学，你好！数据集没有问题，我自己重新从百度下载下来，解压正常（用的360压缩，软件无所谓），请确认你下载的数据集压缩包完整下载（百度云文件限制，分段上传的，需要同时下载完成img.zip img.z01 02 03，之后再解压）,祝好！
